<a href="https://colab.research.google.com/github/Jee8825/jeeva-codebooster-2026/blob/main/Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
print("Lib loaded successfully")

Lib loaded successfully

In [4]:
df=pd.read_csv('Student Performance Day 1.csv')

In [5]:
print(df)

    student_id            name  age  gender        department  semester  \
0         1001    Aarav Sharma   19    Male  Computer Science         2
1         1002     Priya Patel   20  Female  Computer Science         2
2         1003     Rohit Verma   19    Male       Electronics         2
3         1004     Sneha Reddy   20  Female        Mechanical         2
4         1005      Arjun Nair   19    Male  Computer Science         2
5         1006     Meera Joshi   20  Female       Electronics         2
6         1007     Kiran Kumar   21    Male             Civil         2
7         1008     Divya Singh   19  Female  Computer Science         2
8         1009    Rahul Mishra   20    Male        Mechanical         2
9         1010      Ananya Das   19  Female  Computer Science         2
10        1011     Vikram Iyer   20    Male       Electronics         2
11        1012     Pooja Gupta   19  Female             Civil         2
12        1013      Suresh Rao   21    Male  Computer Science         2
13        1014   Kavya Nambiar   20  Female        Mechanical         2
14        1015     Ajay Tiwari   19    Male  Computer Science         2
15        1016    Ritu Agarwal   20  Female       Electronics         2
16        1017    Manoj Pandey   21    Male             Civil         2
17        1018  Swati Kulkarni   19  Female  Computer Science         2
18        1019  Deepak Chauhan   20    Male        Mechanical         2
19        1020    Nisha Kapoor   19  Female  Computer Science         2
20        1021   Harish Pillai   20    Male       Electronics         2
21        1022     Tanvi Mehta   19  Female  Computer Science         2
22        1023    Sanjay Dubey   21    Male             Civil         2
23        1024   Preeti Saxena   20  Female        Mechanical         2
24        1025       Amit Bose   19    Male  Computer Science         2
25        1026      Rekha Nair   20  Female       Electronics         2
26        1027   Gaurav Shukla   21    Male  Computer Science         2
27        1028   Sunita Pillai   19  Female             Civil         2
28        1029      Nitin Jain   20    Male        Mechanical         2
29        1030  Akanksha Yadav   19  Female  Computer Science         2

    math_score  science_score  english_score  programming_score  \
0           85             78             72                 91
1           76             82             88                 79
2           65             74             61                 55
3           70             80             75                 48
4           92             88             81                 95
5           58             66             70                 52
6           73             69             65                 40
7           88             91             84                 93
8           62             71             58                 45
9           95             89             90                 97
10          80             75             68                 72
11          67             72             79                 44
12          83             86             77                 88
13          74             78             82                 51
14          71             69             64                 76
15          87             83             86                 69
16          56             61             55                 38
17          90             87             85                 92
18          68             73             62                 49
19          79             84             81                 83
20          64             70             67                 58
21          93             90             88                 96
22          61             66             59                 42
23          77             81             76                 53
24          86             82             79                 89
25          72             77             73                 63
26          84             79             75                 87
27          60             65             68                 39
28          75             76             70                 50
29          91             93             87                 94

    attendance_percentage                city  admission_year
0                      92              Mumbai            2023
1                      87           Ahmedabad            2023
2                      78               Delhi            2023
3                      95           Hyderabad            2023
4                      90               Kochi            2023
5                      72                Pune            2023
6                      85           Bangalore            2023
7                      96             Lucknow            2023
8                      68            Varanasi            2023
9                      98             Kolkata            2023
10                     83             Chennai            2023
11                     80              Jaipur            2023
12                     88              Mysore            2023
13                     91            Thrissur            2023
14                     75              Bhopal            2023
15                     93                Agra            2023
16                     65               Patna            2023
17                     94              Nagpur            2023
18                     77            Dehradun            2023
19                     89          Chandigarh            2023
20                     74  Thiruvananthapuram            2023
21                     97               Surat            2023
22                     70           Allahabad            2023
23                     86              Kanpur            2023
24                     91             Kolkata            2023
25                     82               Kochi            2023
26                     87             Lucknow            2023
27                     73  Thiruvananthapuram            2023
28                     84              Indore            2023
29                     95                Agra            2023

In [6]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [7]:
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [8]:
df.shape

(30, 13)

In [10]:
df.columns.tolist()

['student_id',
 'name',
 'age',
 'gender',
 'department',
 'semester',
 'math_score',
 'science_score',
 'english_score',
 'programming_score',
 'attendance_percentage',
 'city',
 'admission_year']

In [11]:
df.dtypes

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [12]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [13]:
df.isnull().sum()

student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [14]:
print(df["name"])

0       Aarav Sharma
1        Priya Patel
2        Rohit Verma
3        Sneha Reddy
4         Arjun Nair
5        Meera Joshi
6        Kiran Kumar
7        Divya Singh
8       Rahul Mishra
9         Ananya Das
10       Vikram Iyer
11       Pooja Gupta
12        Suresh Rao
13     Kavya Nambiar
14       Ajay Tiwari
15      Ritu Agarwal
16      Manoj Pandey
17    Swati Kulkarni
18    Deepak Chauhan
19      Nisha Kapoor
20     Harish Pillai
21       Tanvi Mehta
22      Sanjay Dubey
23     Preeti Saxena
24         Amit Bose
25        Rekha Nair
26     Gaurav Shukla
27     Sunita Pillai
28        Nitin Jain
29    Akanksha Yadav
Name: name, dtype: object

In [15]:
print(df['department'].unique())
df['department'].value_counts()

['Computer Science' 'Electronics' 'Mechanical' 'Civil']

department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [16]:
dfcs=df[df['department']=='Computer Science']
print(dfcs)
print(dfcs[['name','math_score','programming_score','attendance_percentage']])

    student_id            name  age  gender        department  semester  \
0         1001    Aarav Sharma   19    Male  Computer Science         2
1         1002     Priya Patel   20  Female  Computer Science         2
4         1005      Arjun Nair   19    Male  Computer Science         2
7         1008     Divya Singh   19  Female  Computer Science         2
9         1010      Ananya Das   19  Female  Computer Science         2
12        1013      Suresh Rao   21    Male  Computer Science         2
14        1015     Ajay Tiwari   19    Male  Computer Science         2
17        1018  Swati Kulkarni   19  Female  Computer Science         2
19        1020    Nisha Kapoor   19  Female  Computer Science         2
21        1022     Tanvi Mehta   19  Female  Computer Science         2
24        1025       Amit Bose   19    Male  Computer Science         2
26        1027   Gaurav Shukla   21    Male  Computer Science         2
29        1030  Akanksha Yadav   19  Female  Computer Science         2

    math_score  science_score  english_score  programming_score  \
0           85             78             72                 91
1           76             82             88                 79
4           92             88             81                 95
7           88             91             84                 93
9           95             89             90                 97
12          83             86             77                 88
14          71             69             64                 76
17          90             87             85                 92
19          79             84             81                 83
21          93             90             88                 96
24          86             82             79                 89
26          84             79             75                 87
29          91             93             87                 94

    attendance_percentage        city  admission_year
0                      92      Mumbai            2023
1                      87   Ahmedabad            2023
4                      90       Kochi            2023
7                      96     Lucknow            2023
9                      98     Kolkata            2023
12                     88      Mysore            2023
14                     75      Bhopal            2023
17                     94      Nagpur            2023
19                     89  Chandigarh            2023
21                     97       Surat            2023
24                     91     Kolkata            2023
26                     87     Lucknow            2023
29                     95        Agra            2023
              name  math_score  programming_score  attendance_percentage
0     Aarav Sharma          85                 91                     92
1      Priya Patel          76                 79                     87
4       Arjun Nair          92                 95                     90
7      Divya Singh          88                 93                     96
9       Ananya Das          95                 97                     98
12      Suresh Rao          83                 88                     88
14     Ajay Tiwari          71                 76                     75
17  Swati Kulkarni          90                 92                     94
19    Nisha Kapoor          79                 83                     89
21     Tanvi Mehta          93                 96                     97
24       Amit Bose          86                 89                     91
26   Gaurav Shukla          84                 87                     87
29  Akanksha Yadav          91                 94                     95

In [18]:
dfcs_high_attendance = dfcs[dfcs['attendance_percentage'] > 90]
print(dfcs_high_attendance[['name','math_score','programming_score','attendance_percentage']])

              name  math_score  programming_score  attendance_percentage
0     Aarav Sharma          85                 91                     92
7      Divya Singh          88                 93                     96
9       Ananya Das          95                 97                     98
17  Swati Kulkarni          90                 92                     94
21     Tanvi Mehta          93                 96                     97
24       Amit Bose          86                 89                     91
29  Akanksha Yadav          91                 94                     95

In [20]:
sorted_df = df.sort_values(by=['department', 'programming_score'], ascending=[True, False])

top_performing_students = sorted_df.groupby('department').head(3)


display(top_performing_students[['department', 'name', 'programming_score']])

          department           name  programming_score
11             Civil    Pooja Gupta                 44
22             Civil   Sanjay Dubey                 42
6              Civil    Kiran Kumar                 40
9   Computer Science     Ananya Das                 97
21  Computer Science    Tanvi Mehta                 96
4   Computer Science     Arjun Nair                 95
10       Electronics    Vikram Iyer                 72
15       Electronics   Ritu Agarwal                 69
25       Electronics     Rekha Nair                 63
23        Mechanical  Preeti Saxena                 53
13        Mechanical  Kavya Nambiar                 51
28        Mechanical     Nitin Jain                 50

In [23]:
result = df.groupby('department')[[
    'math_score',
    'science_score',
    'english_score',
    'programming_score'
]].agg(['max','mean'])

print(result)
max_score = df.groupby('department')[[
    'math_score',
    'science_score',
    'english_score',
    'programming_score'
]].max()

print(max_score)

                 math_score            science_score            english_score  \
                        max       mean           max       mean           max
department
Civil                    73  63.400000            72  66.600000            79
Computer Science         95  85.615385            93  84.461538            90
Electronics              87  71.000000            83  74.166667            86
Mechanical               77  71.000000            81  76.500000            82

                            programming_score
                       mean               max       mean
department
Civil             65.200000                44  40.600000
Computer Science  80.846154                97  89.230769
Electronics       70.833333                72  61.500000
Mechanical        70.500000                53  49.333333
                  math_score  science_score  english_score  programming_score
department
Civil                     73             72             79                 44
Computer Science          95             93             90                 97
Electronics               87             83             86                 72
Mechanical                77             81             82                 53

In [26]:
df['average_subject_score'] = df[['math_score', 'science_score', 'english_score', 'programming_score']].mean(axis=1)
average_score_per_department = df.groupby('department')['average_subject_score'].mean()

print("Average Overall Score per Department:")
display(average_score_per_department.sort_values(ascending=False))

Average Overall Score per Department:

department
Computer Science    85.038462
Electronics         69.375000
Mechanical          66.833333
Civil               58.950000
Name: average_subject_score, dtype: float64

## Pushing this Colab Notebook to GitHub

Here are the general steps to push your Colab notebook to GitHub. Make sure you have a GitHub account and have created a repository where you want to store this notebook.

### Step 1: Save a copy of your notebook to GitHub

1.  Go to `File` > `Save a copy in GitHub...`.
2.  A dialog box will appear. Select your GitHub repository.
3.  Choose the branch you want to commit to (e.g., `main` or `master`).
4.  Add a commit message.
5.  Click `OK`.

This is the simplest way to get your `.ipynb` file into a GitHub repository directly from Colab.

### Alternative: Manual Git commands (for more control or if the above fails)

If you prefer to use Git commands directly within Colab, or if you need to manage a more complex repository, you can do the following. This requires a personal access token for GitHub.

#### 1. Generate a GitHub Personal Access Token (if you don't have one)

*   Go to your GitHub profile settings.
*   Navigate to `Developer settings` > `Personal access tokens` > `Tokens (classic)`.
*   Generate a new token with at least `repo` scope permissions. Copy the token immediately as it won't be shown again.

#### 2. Store your GitHub token securely in Colab secrets

In the left panel of Colab, click on the "🔑 Secrets" tab and add a new secret named `GITHUB_TOKEN` with your personal access token as the value. Make sure 'Notebook access' is enabled.

In [ ]:
from google.colab import userdata
import os

# Retrieve GitHub token from Colab secrets
GITHUB_TOKEN = userdata.get('GITHUB_TOKEN')

# Configure Git with your email and username
# Replace with your actual GitHub email and username
!git config --global user.email "YOUR_GITHUB_EMAIL"
!git config --global user.name "YOUR_GITHUB_USERNAME"

#### 3. Clone your repository

Replace `YOUR_GITHUB_USERNAME` and `YOUR_REPOSITORY_NAME` with your actual GitHub username and repository name.

In [ ]:
# Replace with your GitHub username and repository name
repo_owner = "YOUR_GITHUB_USERNAME"
repo_name = "YOUR_REPOSITORY_NAME"

# Clone the repository using the token for authentication
!git clone https://{GITHUB_TOKEN}@github.com/{repo_owner}/{repo_name}.git

# Change to the repository directory
%cd {repo_name}

#### 4. Save your notebook content

Colab notebooks are usually saved automatically to your Google Drive. To commit this specific notebook's current state, you might need to manually save it or download it and re-upload it to the cloned directory, or use a command to copy it. For simplicity, if you've cloned the repo into a temporary Colab environment, you would typically download the `.ipynb` file from `File` > `Download` > `.ipynb` and then manually upload it to the correct path within your cloned repository folder in the Colab file browser (the folder icon on the left).

If you want to save the *current state of the notebook you are working on* into the cloned repository programmatically, it's a bit more complex. A common approach is to download it to the Colab environment and then move it:

1.  **Download the current notebook content:** This usually happens in the browser, but you can use `!cp` if it's already in `/content/`.
    *   First, get the current notebook's filename. It's usually something like `Untitled0.ipynb` or `YourNotebookName.ipynb`.
    *   Let's assume the notebook file is `my_analysis.ipynb`.
2.  **Copy it to your cloned repository:**

In [ ]:
# Assuming your current notebook is saved as 'my_analysis.ipynb' in the /content/ directory
# and you want to save it into the root of your cloned repository.
# You might need to change 'my_analysis.ipynb' to the actual name of this notebook file in your Colab environment.

# !cp "/content/my_analysis.ipynb" .

# A more robust way to get the current notebook's path and then copy it
# This often requires manual identification of the current notebook's file name from the Google Drive/Colab UI
# For example, if your notebook is named 'Untitled0.ipynb' and it's saved in your Drive, it might be in a temporary '/content/' path after opening.
# For the purpose of demonstration, let's create a dummy file to simulate the notebook content if you were to manually copy it.

# Create a dummy file or copy your actual notebook content here
# Example: If your notebook was downloaded and then uploaded to the root of your cloned repo folder
# Or, if you use the 'File -> Save a copy in GitHub' method, this step is handled.

# !echo "This is my notebook content." > "my_analysis.ipynb" # This is just a placeholder example

#### 5. Add, commit, and push changes

In [ ]:
# Add all changed files
!git add .

# Commit the changes
# Replace with your desired commit message
!git commit -m "Update notebook from Colab"

# Push to the remote repository (e.g., 'origin' and 'main' branch)
!git push origin main

Remember to replace placeholder values like `YOUR_GITHUB_EMAIL`, `YOUR_GITHUB_USERNAME`, `YOUR_REPOSITORY_NAME`, and potentially the notebook filename with your actual information.