<a href="https://colab.research.google.com/github/Jee8825/jeeva-codebooster-2026/blob/main/Day_3/Day_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
!pip install requests --quiet
import requests
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [5]:
df=pd.read_csv('Sales Data Day 2.csv')
df.head()

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma
1,1002,Priya Nair,NaN,Electronics,1.0,15000,2024-01-07,Delhi,Sunita Rao
2,1003,AMIT VERMA,Keyboard,Accessories,3.0,1200,2024-01-08,Bangalore,Anil Sharma
3,1004,Sunita Patel,Monitor,Electronics,NaN,22000,2024-01-10,Chennai,Ravi Kumar
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma

In [6]:
# 1. Check for missing values
print("Missing values per column:")
display(df.isnull().sum())

# 2. Check for duplicates
duplicate_count = df.duplicated().sum()
print(f"\nNumber of duplicate rows: {duplicate_count}")
if duplicate_count > 0:
    df = df.drop_duplicates()
    print("Duplicates removed.")

Missing values per column:

order_id         0
customer_name    2
product          1
category         1
quantity         3
unit_price       0
order_date       0
city             0
sales_rep        0
dtype: int64

Number of duplicate rows: 0

In [9]:
# 3. Data Types Conversion
# Using dayfirst=True and format='mixed' to handle inconsistent date strings like '07-01-2024'
df['order_date'] = pd.to_datetime(df['order_date'], dayfirst=True, format='mixed')

print("\nUpdated Data Types:")
display(df.dtypes)

Updated Data Types:

order_id                  int64
customer_name            object
product                  object
category                 object
quantity                float64
unit_price                int64
order_date       datetime64[ns]
city                     object
sales_rep                object
dtype: object

In [10]:

df['product'] = df['product'].fillna('Unknown')
df['category'] = df['category'].fillna('Unknown')

df['quantity'] = df['quantity'].fillna(df['quantity'].median())


df = df.dropna(subset=['customer_name'])

print("Missing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
order_id         0
customer_name    0
product          0
category         0
quantity         0
unit_price       0
order_date       0
city             0
sales_rep        0
dtype: int64

In [8]:
# 4. Unique values in text columns
text_columns = ['product', 'category', 'city', 'sales_rep']
print("\nUnique values in text columns:")
for col in text_columns:
    if col in df.columns:
        unique_vals = df[col].dropna().unique()
        print(f"{col}: {unique_vals}")

Unique values in text columns:
product: ['Laptop' 'Keyboard' 'Monitor' 'Mouse' 'Headphones' 'Webcam' 'USB Hub']
category: ['Electronics' 'Accessories']
city: ['Mumbai' 'Delhi' 'Bangalore' 'Chennai' 'Pune' 'Hyderabad' 'Kolkata'
 'Kochi' 'Surat' 'Lucknow' 'Chandigarh' 'Bhopal' 'Kanpur'
 'Thiruvananthapuram' 'Allahabad' 'Thrissur']
sales_rep: ['Anil Sharma' 'Sunita Rao' 'Ravi Kumar']

In [12]:
df['quantity'].duplicated().sum()

np.int64(19)

In [14]:
cp_df=df.copy()

In [15]:

df['product'] = df['product'].fillna('Unknown')
df['category'] = df['category'].fillna('Unknown')

df['quantity'] = df['quantity'].fillna(df['quantity'].median())

df = df.dropna(subset=['customer_name'])

print("Missing values after handling:")
print(df.isnull().sum())

Missing values after handling:
order_id         0
customer_name    0
product          0
category         0
quantity         0
unit_price       0
order_date       0
city             0
sales_rep        0
dtype: int64

In [17]:
df['order_date'] = pd.to_datetime(df['order_date'], dayfirst=True, format='mixed')

print("Date column parsed successfully.")
print(df[['order_date']].info())

Date column parsed successfully.
<class 'pandas.core.frame.DataFrame'>
Index: 28 entries, 0 to 29
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_date  28 non-null     datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 448.0 bytes
None

In [18]:
df['formatted_date'] = df['order_date'].dt.strftime('%d/%m/%Y')

display(df[['order_date', 'formatted_date']].head())

  order_date formatted_date
0 2024-01-05     05/01/2024
1 2024-01-07     07/01/2024
2 2024-01-08     08/01/2024
3 2024-01-10     10/01/2024
4 2024-01-05     05/01/2024

In [22]:
df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month
df['month_name'] = df['order_date'].dt.month_name()

display(df[['order_date', 'year', 'month', 'month_name']].head(20))

   order_date  year  month month_name
0  2024-01-05  2024      1    January
1  2024-01-07  2024      1    January
2  2024-01-08  2024      1    January
3  2024-01-10  2024      1    January
4  2024-01-05  2024      1    January
5  2024-01-07  2024      1    January
6  2024-01-12  2024      1    January
8  2024-01-15  2024      1    January
9  2024-01-15  2024      1    January
10 2024-01-18  2024      1    January
11 2024-01-20  2024      1    January
12 2024-01-22  2024      1    January
13 2024-01-21  2024      1    January
14 2024-01-25  2024      1    January
15 2024-01-07  2024      1    January
16 2024-01-28  2024      1    January
17 2024-01-30  2024      1    January
18 2024-02-01  2024      2   February
19 2024-02-03  2024      2   February
20 2024-02-05  2024      2   February

In [31]:
df['revenue']=df['quantity']*df['unit_price']
display(df[['customer_name','product','quantity','unit_price','revenue']].head(31))
print(df['revenue'].sum())

   customer_name     product  quantity  unit_price   revenue
0    Ramesh K***      Laptop       2.0       45000   90000.0
1     Priya N***     Unknown       1.0       15000   15000.0
2      Amit V***    Keyboard       3.0        1200    3600.0
3    Sunita P***     Monitor       2.0       22000   44000.0
4    Ramesh K***      Laptop       2.0       45000   90000.0
5     Kiran M***       Mouse      10.0         800    8000.0
6    Deepak S***  Headphones       2.0        3500    7000.0
8    Ananya D***      Laptop       1.0       45000   45000.0
9    Vikram I***    Keyboard       5.0        1200    6000.0
10    Pooja G***     Monitor       2.0       22000   44000.0
11   Suresh R***     Usb Hub       8.0         600    4800.0
12    Meera J***      Laptop       2.0       45000   90000.0
13    Arjun N***  Headphones       3.0        3500   10500.0
14    Tanvi M***      Webcam       2.0        2500    5000.0
15    Kiran M***       Mouse      10.0         800    8000.0
16   Deepak S***    Keyboard       5.0        1200    6000.0
17    Rohit V***     Monitor       1.0       22000   22000.0
18    Sneha R***      Laptop       1.0       45000   45000.0
19   Gaurav S***     Usb Hub      15.0         600    9000.0
20    Nisha K***  Headphones       2.0        3500    7000.0
21     Ajay T***      Webcam       3.0        2500    7500.0
22   Ananya D***      Laptop       1.0       45000   45000.0
23   Preeti S***    Keyboard       4.0        1200    4800.0
24     Amit B***       Mouse       6.0         800    4800.0
26    Rekha N***     Monitor       2.0       22000   44000.0
27   Harish P***      Laptop       3.0       45000  135000.0
28   Sanjay D***     Usb Hub      10.0         600    6000.0
29    Kavya N***      Webcam       2.0        2500    5000.0

812000.0

In [21]:
df['day_name'] = df['order_date'].dt.day_name()

display(df[['order_date', 'day_name']].head(10))

   order_date   day_name
0  2024-01-05     Friday
1  2024-01-07     Sunday
2  2024-01-08     Monday
3  2024-01-10  Wednesday
4  2024-01-05     Friday
5  2024-01-07     Sunday
6  2024-01-12     Friday
8  2024-01-15     Monday
9  2024-01-15     Monday
10 2024-01-18   Thursday

In [23]:
text_cols = ['customer_name', 'product', 'category', 'city', 'sales_rep']
for col in text_cols:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip().str.title()

def mask_name(name):
    parts = name.split()
    if len(parts) > 1:
        return f"{parts[0]} {parts[1][0]}***"
    return f"{parts[0][0]}***"

df['customer_name'] = df['customer_name'].apply(mask_name)

print("Text standardized and names masked.")
display(df[['customer_name', 'product', 'city', 'sales_rep']].head(10))

Text standardized and names masked.

   customer_name     product       city    sales_rep
0    Ramesh K***      Laptop     Mumbai  Anil Sharma
1     Priya N***     Unknown      Delhi   Sunita Rao
2      Amit V***    Keyboard  Bangalore  Anil Sharma
3    Sunita P***     Monitor    Chennai   Ravi Kumar
4    Ramesh K***      Laptop     Mumbai  Anil Sharma
5     Kiran M***       Mouse       Pune   Sunita Rao
6    Deepak S***  Headphones  Hyderabad   Ravi Kumar
8    Ananya D***      Laptop    Kolkata   Sunita Rao
9    Vikram I***    Keyboard    Chennai   Ravi Kumar
10    Pooja G***     Monitor      Delhi  Anil Sharma

In [24]:
comparison_df = pd.DataFrame()

comparison_df['Standardized Name'] = cp_df['customer_name'].dropna().astype(str).str.strip().str.title()

comparison_df['Masked Name'] = comparison_df['Standardized Name'].apply(mask_name)

display(comparison_df.head(10))

   Standardized Name  Masked Name
0       Ramesh Kumar  Ramesh K***
1         Priya Nair   Priya N***
2         Amit Verma    Amit V***
3       Sunita Patel  Sunita P***
4       Ramesh Kumar  Ramesh K***
5        Kiran Mehta   Kiran M***
6       Deepak Singh  Deepak S***
8         Ananya Das  Ananya D***
9        Vikram Iyer  Vikram I***
10       Pooja Gupta   Pooja G***

In [34]:
print("--- Missing Values Check ---")
print(df.isnull().sum())

print("\n--- Masking Validation (Sample) ---")
display(df[['customer_name']].head())

print("\n--- New Columns Validation ---")
new_cols = ['year', 'month_name', 'day_name', 'revenue']
display(df[new_cols].describe(include='all'))

clean = (df.isnull().sum() == 0).all() and (df.duplicated().sum() == 0)
print(f"\nData is clean: {clean}")

print(f"\nFinal Row Count: {len(df)}")
print(f"Total Revenue across all records: ‡{df['revenue'].sum():,.2f}")

--- Missing Values Check ---
order_id          0
customer_name     0
product           0
category          0
quantity          0
unit_price        0
order_date        0
city              0
sales_rep         0
formatted_date    0
year              0
month             0
month_name        0
day_name          0
revenue           0
dtype: int64

--- Masking Validation (Sample) ---

  customer_name
0   Ramesh K***
1    Priya N***
2     Amit V***
3   Sunita P***
4   Ramesh K***

--- New Columns Validation ---

          year month_name day_name        revenue
count     28.0         28       28      28.000000
unique     NaN          2        7            NaN
top        NaN    January   Monday            NaN
freq       NaN         18        7            NaN
mean    2024.0        NaN      NaN   29000.000000
std        0.0        NaN      NaN   34578.188372
min     2024.0        NaN      NaN    3600.000000
25%     2024.0        NaN      NaN    6000.000000
50%     2024.0        NaN      NaN    8500.000000
75%     2024.0        NaN      NaN   44250.000000
max     2024.0        NaN      NaN  135000.000000

Data is clean: True

Final Row Count: 28
Total Revenue across all records: ‡812,000.00

In [36]:
df.to_csv('Cleaned_Sales_Data.csv', index=False)
print('File saved as Cleaned_Sales_Data.csv')

File saved as Cleaned_Sales_Data.csv